#!/bin/bash

cd $(dirname $BASH_SOURCE)
cd ..
PLUG_SRC=$(pwd)/plug.vim
cd - > /dev/null

if [ ! -d vader.vim ]; then
  git clone https://github.com/junegunn/vader.vim.git
fi

cat > /tmp/mini-vimrc << VIMRC
set rtp+=vader.vim
source $PLUG_SRC
VIMRC

if [ "$1" = '!' ]; then
  /usr/local/bin/vim -Nu /tmp/mini-vimrc -c 'Vader! workflow.vader' > /dev/null
else
  /usr/local/bin/vim -Nu /tmp/mini-vimrc -c 'Vader workflow.vader'
fi

